In [1]:
import csv
import numpy as np

In [2]:
race_name = 'France'
n_teams = 100
n_riders = 9

# Finding the best team with manual filtering
# Italy: 7, 10, 8, 12 (37)  4'13''
# France: 7, 17, 10, 12 (46)  18'26''
# Spain: 8, 11, 5, 12 (36)  4'09''

# Finding the best 1/10/25 teams with logic filtering but no top-cost filtering
# Italy: 9, 11, 8, 12 (40)  16'46'' (10) / 22'33'' (25) / 56'55'' (100)
# France: 16, 17, 10, 12 (55)  2h 26'20''  4h 33'44'' (10)
# Spain: 10, 15, 5, 12 (42)  26'18'' (10) / 35'38'' (25) / 1h 18'29'' (100)

# Finding the best 100 teams with logic and top-cost filtering
# Italy: 7, 10, 7, 12 (36)  21'15''
# France: 10, 13, 8, 10 (41)  56'03''
# Spain: 8, 13, 4, 12 (37)  27'54''

# Top 100 with ratio filtering
# Italy: 8, 8, 6, 35 (57)  > 11.5h
# France: 9, 14, 13, 16 (52)  ~ 8h
# Spain: 7, 12, 6, 24 (49)  ~ 8h

# Top 100 with adapted filtering
# France: 4, 14, 11, 32 (61)  11h 45m
# Italy: 5, 8, 5, 32 (50)  ~ 2h
# Spain: 6, 12, 3, 32 (53)  ~ 4h

In [3]:
def initialise (n_teams, default):
    set = []
    for d in range(n_teams):
        set.append(default)
    return set

In [4]:
def assignment (set, comb, n_teams, index, default):
    new_set = initialise(n_teams, default)
    inter = set[0:index]
    
    if inter != []:
        new_set[0:index] = inter
        
    new_set[index] = comb
    
    for r in range(index+1, n_teams):
        new_set[r] = set[r-1]
    
    return new_set

In [5]:
def sorting (into, info_w):
    out_ar = sorted([into[0], into[1]])
    out_c = sorted([into[2], into[3]])
    out_s = [into[4]]
    out_u = sorted([into[5], into[6], into[7]])
                    
    for row in range(len(info_w)):
        if into[8] == info_w[row]['Name']:
            j = row
            break
    
    if j+1 <= n_ar:
        out_ar.append(into[8])
        out_ar = sorted(out_ar)
    elif j+1 <= n_ar + n_c:
        out_c.append(into[8])
        out_c = sorted(out_c)
    elif j+1 <= n_ar + n_c + n_s:
        out_s.append(into[8])
        out_s = sorted(out_s)
    else:
        out_u.append(into[8])
        out_u = sorted(out_u)
        
    return out_ar, out_c, out_s, out_u

In [6]:
def checker (comb_riders, set_riders, info_w, n_teams):
    [comb_ar_sort, comb_c_sort, comb_s_sort, comb_u_sort] = sorting(comb_riders, info_w)
    
    for team in range(n_teams):
        if set_riders[team] != []:
            [set_ar_sort, set_c_sort, set_s_sort, set_u_sort] = sorting(set_riders[team], info_w)
            unique = True
            counter = 0
            if comb_ar_sort == set_ar_sort:
                counter += 1
            if comb_c_sort == set_c_sort:
                counter += 1
            if comb_s_sort == set_s_sort:
                counter += 1
            if comb_u_sort == set_u_sort:
                counter += 1
            if counter == 4:
                unique = False
                break
        else:
            unique = True
            
    return unique

In [7]:
# For All Rounders
allrounder_file = open(race_name + '_Allrounder' + '_Top.txt', 'r')
info_ar = []
l_ar = 0

data = csv.DictReader(allrounder_file)
for row in data:
    info_ar.append(row)
    info_ar[l_ar]['Cost'] = int(info_ar[l_ar]['Cost'])
    info_ar[l_ar]['Points'] = int(info_ar[l_ar]['Points'])
    l_ar += 1
       
allrounder_file.close()

# For Climbers
climber_file = open(race_name + '_Climber' + '_Top.txt', 'r')
info_c = []
l_c = 0

data = csv.DictReader(climber_file)
for row in data:
    info_c.append(row)
    info_c[l_c]['Cost'] = int(info_c[l_c]['Cost'])
    info_c[l_c]['Points'] = int(info_c[l_c]['Points'])
    l_c += 1
       
climber_file.close()

# For Sprinters
sprinter_file = open(race_name + '_Sprinter' + '_Top.txt', 'r')
info_s = []
l_s = 0

data = csv.DictReader(sprinter_file)
for row in data:
    info_s.append(row)
    info_s[l_s]['Cost'] = int(info_s[l_s]['Cost'])
    info_s[l_s]['Points'] = int(info_s[l_s]['Points'])
    l_s += 1
       
sprinter_file.close()

# For Unclassified
unclassified_file = open(race_name + '_Unclassified' + '_Top.txt', 'r')
info_u = []
l_u = 0

data = csv.DictReader(unclassified_file)
for row in data:
    info_u.append(row)
    info_u[l_u]['Cost'] = int(info_u[l_u]['Cost'])
    info_u[l_u]['Points'] = int(info_u[l_u]['Points'])
    l_u += 1
       
unclassified_file.close()

# For Wildcard
wildcard_file = open(race_name + '_Wildcard' + '_Top.txt', 'r')
info_w = []
l_w = 0

data = csv.DictReader(wildcard_file)
for row in data:
    info_w.append(row)
    info_w[l_w]['Cost'] = int(info_w[l_w]['Cost'])
    info_w[l_w]['Points'] = int(info_w[l_w]['Points'])
    l_w += 1
       
wildcard_file.close()

n_ar = len(info_ar)
n_c = len(info_c)
n_s = len(info_s)
n_u = len(info_u)
n_all = n_ar + n_c + n_s + n_u

In [8]:
set_riders = initialise(n_teams, [])
set_scores = initialise(n_teams, 0)
set_costs = initialise(n_teams, 0)

for ar1 in range(n_ar-1):
    print(ar1)
    for ar2 in range(ar1+1,n_ar):
        for c1 in range(n_c-1):
            for c2 in range(c1+1,n_c):
                for s in range(n_s):
                    for u1 in range(n_u-2):
                        for u2 in range(u1+1,n_u-1):
                            for u3 in range(u2+1,n_u):
                                for w in range(n_all):
                                    if w != ar1 and w != ar2 and w != c1+n_ar and w != c2+n_ar and w != s+n_ar+n_c and w != u1+n_ar+n_c+n_s and w != u2+n_ar+n_c+n_s and w != u3+n_ar+n_c+n_s:
                                        comb_cost = info_ar[ar1]['Cost'] + info_ar[ar2]['Cost'] + info_c[c1]['Cost'] + info_c[c2]['Cost'] + info_s[s]['Cost'] + info_u[u1]['Cost'] + info_u[u2]['Cost'] + info_u[u3]['Cost'] + info_w[w]['Cost']
                                        if comb_cost <= 100:
                                            comb_riders = [info_ar[ar1]['Name'], info_ar[ar2]['Name'], info_c[c1]['Name'], info_c[c2]['Name'], info_s[s]['Name'], info_u[u1]['Name'], info_u[u2]['Name'], info_u[u3]['Name'], info_w[w]['Name']]
                                            comb_score = info_ar[ar1]['Points'] + info_ar[ar2]['Points'] + info_c[c1]['Points'] + info_c[c2]['Points'] + info_s[s]['Points'] + info_u[u1]['Points'] + info_u[u2]['Points'] + info_u[u3]['Points'] + info_w[w]['Points']
                                            for index in range(n_teams):
                                                if comb_score > set_scores[index]:
                                                    unique = checker(comb_riders, set_riders, info_w, n_teams)
                                                    if unique:
                                                        set_riders = assignment(set_riders, comb_riders, n_teams, index, [])
                                                        set_scores = assignment(set_scores, comb_score, n_teams, index, 0)
                                                        set_costs = assignment(set_costs, comb_cost, n_teams, index, 0)
                                                
print('Evaluation of all the combinations complete.')

0
1
2
3
4
5
6
7
Evaluation of all the combinations complete.


In [9]:
out_file = open(str(race_name) + '_Top' + str(n_teams) + '.txt', 'w')
for team in range(n_teams):
    out_file.write('Team number ' + str(team+1) + ':' + '\n')
    for rider in range(n_riders):
        out_file.write(set_riders[team][rider] + '\n')
    out_file.write('Scoring ' + str(set_scores[team]) + ' points.' + '\n')
    out_file.write('Costing ' + str(set_costs[team]) + ' credits.' + '\n')
    out_file.write('\n')
out_file.close()

In [10]:
distribution = np.zeros((n_all,4))

for team in range(10):
    for rider in range(n_riders):
        for row in range(n_all):
            if set_riders[team][rider] == info_w[row]['Name']:
                distribution[row,0] += 1
                break
for team in range(25):
    for rider in range(n_riders):
        for row in range(n_all):
            if set_riders[team][rider] == info_w[row]['Name']:
                distribution[row,1] += 1
                break
for team in range(50):
    for rider in range(n_riders):
        for row in range(n_all):
            if set_riders[team][rider] == info_w[row]['Name']:
                distribution[row,2] += 1
                break
for team in range(100):
    for rider in range(n_riders):
        for row in range(n_all):
            if set_riders[team][rider] == info_w[row]['Name']:
                distribution[row,3] += 1
                break

In [11]:
out_file = open(str(race_name) + '_Distribution.txt', 'w')
for row in range(n_all):
    if distribution[row,3] != 0:
        out_file.write(info_w[row]['Name'] + ',' + str(int(distribution[row,0])) + ',' + str(int(distribution[row,1])) + ',' + str(int(distribution[row,2])) + ',' + str(int(distribution[row,3])) + '\n')
out_file.close()

In [12]:
print(distribution)

[[ 10.  25.  50. 100.]
 [ 10.  25.  50. 100.]
 [  0.   0.   0.   2.]
 [  0.   0.   0.   0.]
 [  7.  17.  32.  68.]
 [  0.   0.   0.   0.]
 [ 10.  23.  45.  86.]
 [  3.   8.  20.  35.]
 [  0.   2.   3.   9.]
 [  0.   0.   0.   0.]
 [ 10.  25.  50. 100.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   1.   3.   7.]
 [  0.   0.   0.   0.]
 [ 10.  24.  47.  93.]
 [  0.   0.   0.   0.]
 [  3.  10.  21.  40.]
 [  0.   0.   1.   1.]
 [  0.   0.   0.   1.]
 [  9.  20.  40.  68.]
 [  4.  10.  15.  32.]
 [  4.   8.  15.  31.]
 [  2.   5.  12.  22.]
 [  1.   2.   5.  14.]
 [  0.   1.   3.   6.]
 [  0.   1.   3.   6.]
 [  0.   1.   2.   5.]
 [  0.   0.   1.   2.]
 [  0.   0.   1.   2.]
 [  0.   0.   0.   1.]
 [  0.   0.   0.   1.]
 [  0.   0.   0.   1.]
 [  0.   0.   0.   1.]
 [  0.   0.   0.   1.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.